name: Aksoum Bot Weekly
on: [workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install requests beautifulsoup4 resend
      - env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: python bot.py